TREEROOT = ../freertos_linux_devl

# PROJECT_SRC = queue_transmit.c
PROJECT_SRC = queue_struct.c

PROJECT = queue

# need to include this makefile for common setting for all program
include $(TREEROOT)/Makefile.common
