TREEROOT = ../freertos_linux_devl

# PROJECT_SRC = block_receiving.c
PROJECT_SRC = block_sending.c

PROJECT = queue

# need to include this makefile for common setting for all program
include $(TREEROOT)/Makefile.common
